[build]
builder = "nixpacks"
buildCommand = "chmod +x scripts/build.sh && ./scripts/build.sh"

[deploy]
startCommand = "python -m uvicorn enablebot.web.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { }